### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by agumonkey** [krockode/x_x#2]
```
$ wget "www.econ.yale.edu/~shiller/data/ie_data.xls"

$ x_x ie_data.xls

<Correct table output for many pages such as >

| 1877.04 | 2.94 | 0.2633 | 0.2867 | 10.46599504 | 1877.291666666661  | 4.4225             | 65.678875479383   | 5.8820571135107285 | 6.404807346918063  | NA |
| 1877.05 | 2.94 | 0.2542 | 0.2883 | 10.65632562 | 1877.3749999999943 | 4.413333333333333  | 64.50579773105694 | 5.5773380215083925 | 6.325517512198543  | NA |
| 1877.06 | 2.73 | 0.245  | 0.29   | 10.08541488 | 1877.4583333333276 | 4.404166666666667  | 63.28893407903116 | 5.679776135297669  | 6.723000323413566  | NA |
| 1877.07 | 2.85 | 0.2358 | 0.2917 | 10.18058017 | 1877.5416666666608 | 4.395              | 65.45325279826366 | 5.415395442045814  | 6.6991978390363185 | NA |
| 1877.08 | 3.05 | 0.2267 | 0.2933 | 9.8         | 1877.624999999994  | 4.385833333333333  | 72.76669770408162 | 5.40859356377551   | 6.997531946428571  | NA |
| 1877.09 | 3.24 | 0.2175 | 0.295  | 9.704834711 | 1877.7083333333273 | 4.376666666666667  | 78.05770346004608 | 5.239984723012353  | 7.107105716269627  | NA |
| 1877.1  | 3.31 | 0.2083 | 0.2967 | 9.704834711 | 1877.7916666666606 | 4.367500000000001  | 79.74413532492362 | 5.018339392199876  | 7.148061918702368  | NA |
| 1877.11 | 3.26 | 0.1992 | 0.2983 | 9.514585124 | 1877.8749999999939 | 4.358333333333333  | 80.10998431002108 | 4.895064071949754  | 7.330309300515119  | NA |
| 1877.12 | 3.25 | 0.19   | 0.3    | 9.514585124 | 1877.9583333333271 | 4.349166666666666  | 79.86424816183084 | 4.668986815614726  | 7.372084445707461  | NA |
| 1878.01 | 3.25 | 0.1892 | 0.3008 | 9.229089256 | 1878.0416666666604 | 4.34               | 82.33479668711529 | 4.793151856369911  | 7.620402105687469  | NA |
| 1878.02 | 3.18 | 0.1883 | 0.3017 | 9.134004959 | 1878.1249999999936 | 4.33               | 81.4000702142601  | 4.8200104469638925 | 7.722767667812036  | NA |

<Pressing q to exit `less` gives>

Traceback (most recent call last):
  File "/home/self/code/python-all/venv/bin/x_x", line 9, in <module>
    load_entry_point('x-x==0.7', 'console_scripts', 'x_x')()
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/x_x/x_x.py", line 46, in cli
    asciitable.draw(XCursor(sheet, heading), out=out)
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/x_x/asciitable.py", line 157, in draw
    write_bytes(value, out)
  File "/home/self/code/python-all/venv/lib/python3.4/site-packages/x_x/asciitable.py", line 16, in write_bytes
    out.write(s)
BrokenPipeError: [Errno 32] Broken pipe
```

## Various data

$ python --version
Python 3.4.3

$ uname -a
Linux x61s_GPT 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64 GNU/Linux

$ pip --version
pip 1.5.6 from /home/self/code/venv/lib/python3.4/site-packages (python 3.4)

**Comment by krockode** [comment]
looks like the python code barfs if you quit less before all the data has been written to it (cannot write to a closed stdout).

**Comment by agumonkey** [comment]
Would a try / except block patch do ?

**Comment by krockode** [comment]
I think so, feel free to send a pull request if you like!

**Comment by krockode** [comment]
Fixed in [PR 3](https://github.com/krockode/x_x/pull/3)
